### Simple Matrix Operations

Consider the following matrices:

$$
X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
Y = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

1. **Addition**:  
$$
X + Y = \begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}
$$

2. **Subtraction**:  
$$
X - Y = \begin{bmatrix} 1-5 & 2-6 \\ 3-7 & 4-8 \end{bmatrix} = \begin{bmatrix} -4 & -4 \\ -4 & -4 \end{bmatrix}
$$

3. **Element-wise Multiplication (Hadamard Product)**:  
$$
X \cdot Y = \begin{bmatrix} 1 \times 5 & 2 \times 6 \\ 3 \times 7 & 4 \times 8 \end{bmatrix} = \begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix}
$$

4. **Matrix Multiplication**:  
$$
X \times Y = \begin{bmatrix} (1 \times 5 + 2 \times 7) & (1 \times 6 + 2 \times 8) \\ (3 \times 5 + 4 \times 7) & (3 \times 6 + 4 \times 8) \end{bmatrix} = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$

5. **Scalar Multiplication**:  
Let \( c = 2 \),  
$$
c \times X = \begin{bmatrix} 2 \times 1 & 2 \times 2 \\ 2 \times 3 & 2 \times 4 \end{bmatrix} = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}
$$


In [ ]:
import numpy as np

# Define Matrices
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

# Addition
Z_add = X + Y
print("Addition:\n", Z_add)

# Subtraction
Z_sub = X - Y
print("Subtraction:\n", Z_sub)

# Element-wise Multiplication
Z_mult = X * Y
print("Element-wise Multiplication:\n", Z_mult)

# Matrix Multiplication
Z_mult = np.dot(X, Y)
print("Matrix Multiplication:\n", Z_mult)

# Scalar Multiplication
c = 2
Z_scalar = c * X
print("Scalar Multiplication:\n", Z_scalar)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Scalar Multiplication:
 [[2 4]
 [6 8]]


### Transpose & Identity Matrix Operations

  Consider the matrix \( X \):

$$
X = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}
$$

1. **Transpose**:  
   The transpose of a matrix \( X \) is denoted as \( X^T \), and it is obtained by swapping rows and columns.

$$
X^T = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

2. **Transpose of Transpose**:  
   Taking the transpose of the transpose of a matrix brings you back to the original matrix:

$$
(X^T)^T = X
$$

3. **Symmetric Matrix**:  
   A matrix \( X \) is symmetric if \( X = X^T \).  
   For example:

$$
X = \begin{bmatrix} 1 & 2 \\ 2 & 1 \end{bmatrix}
\quad \text{because} \quad X^T = X
$$

4. **Identity Matrix**:  
   The identity matrix \( I \) is a square matrix where the diagonal elements are 1 and all other elements are 0. For a 2x2 matrix:

$$
I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
$$

5. **Identity Matrix Multiplication**:  
   Multiplying any matrix \( X \) by the identity matrix results in the matrix itself:

$$
X \times I = I \times X = X
$$


In [ ]:
import numpy as np

# Define Matrix X
X = np.array([[1, 2], [3, 4]])

# Transpose of X
X_transpose = X.T

# Transpose of Transpose (should be same as X)
X_transpose_transpose = X.T.T

# Symmetric Matrix Example
Sym_X = np.array([[1, 2], [2, 1]])

# Identity Matrix
I = np.eye(2)  # 2x2 Identity Matrix

# Identity Matrix Multiplication
X_times_I = np.dot(X, I)
I_times_X = np.dot(I, X)

print("X Transpose:\n", X_transpose)
print("Transpose of Transpose:\n", X_transpose_transpose)
print("Symmetric Matrix Example:\n", Sym_X)
print("Identity Matrix:\n", I)
print("X * I:\n", X_times_I)
print("I * X:\n", I_times_X)


X Transpose:
 [[1 3]
 [2 4]]
Transpose of Transpose:
 [[1 2]
 [3 4]]
Symmetric Matrix Example:
 [[1 2]
 [2 1]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
X * I:
 [[1. 2.]
 [3. 4.]]
I * X:
 [[1. 2.]
 [3. 4.]]


### Inverse & Determinants: Step-by-Step Calculation

Consider the matrix \( X \):

$$
X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

---

### 1. **Inverse of \( X \)**

To find the inverse of a 2x2 matrix, we use the formula:

$$
X^{-1} = \frac{1}{|X|} \cdot \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}
$$

Where \( |X| \) is the determinant of \( X \) and \( a, b, c, d \) are the elements of \( X \):

$$
X = \begin{bmatrix} a & b \\ c & d \end{bmatrix} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

- \( a = 1, b = 2, c = 3, d = 4 \)

Now, let's calculate the determinant \( |X| \):

$$
|X| = (a \cdot d) - (b \cdot c) = (1 \cdot 4) - (2 \cdot 3) = 4 - 6 = -2
$$

Since the determinant \( |X| \) is not zero, \( X \) is invertible.

Now, we can compute the inverse:

$$
X^{-1} = \frac{1}{|X|} \cdot \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix} = \frac{1}{-2} \cdot \begin{bmatrix} 4 & -2 \\ -3 & 1 \end{bmatrix}
$$

Thus, the inverse of \( X \) is:

$$
X^{-1} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

---

### 2. **Inverse of Inverse**

By the property of matrix inverses:

$$
(X^{-1})^{-1} = X
$$

This means that taking the inverse of the inverse of a matrix brings you back to the original matrix. So:

$$
(X^{-1})^{-1} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

---

### 3. **Inverse of Matrix Product**

If we have two matrices \( X \) and \( Y \), the inverse of the product of \( X \) and \( Y \) is:

$$
(XY)^{-1} = Y^{-1} X^{-1}
$$

However, note that:

$$
(YX)^{-1} \neq X^{-1} Y^{-1}
$$

This property holds when the matrices are square and invertible, but the order of multiplication matters.

---

### 4. **Inverse of Transpose**

The inverse of the transpose of a matrix is equal to the transpose of the inverse:

$$
(X^T)^{-1} = (X^{-1})^T
$$

If we calculate the transpose of \( X \):

$$
X^T = \begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}
$$

The inverse of the transpose is:

$$
(X^T)^{-1} = \begin{bmatrix} -2 & 1 \\ 1.5 & -0.5 \end{bmatrix}
$$

Thus:

$$
(X^T)^{-1} = (X^{-1})^T
$$

---

### Determinants: Step-by-Step Calculation

The determinant of a matrix \( A \) is denoted as \( |A| \). For a 2x2 matrix, the determinant is calculated as:

$$
|A| = \begin{vmatrix} a & b \\ c & d \end{vmatrix} = (a \cdot d) - (b \cdot c)
$$

For the matrix \( X \):

$$
X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

The determinant is:

$$
|X| = (1 \cdot 4) - (2 \cdot 3) = 4 - 6 = -2
$$

---

### Minor, Cofactor, and Adjoint Calculation

The **minor** \( M_{ij} \) of an element \( a_{ij} \) is the determinant of the submatrix obtained by removing the \( i \)-th row and \( j \)-th column. For a 2x2 matrix, the minor is the determinant of the 1x1 submatrix after deleting the row and column containing the element.

The **cofactor** \( A_{ij} \) is calculated as:

$$
A_{ij} = (-1)^{i+j} M_{ij}
$$

For matrix \( X \):

1. **Minor of \( a_{11} \)**:  
   The minor \( M_{11} \) is the determinant of the matrix obtained by deleting the first row and first column:

$$
M_{11} = \begin{vmatrix} 4 \end{vmatrix} = 4
$$

Thus, the cofactor \( A_{11} \) is:

$$
A_{11} = (-1)^{1+1} M_{11} = 1 \times 4 = 4
$$

2. **Minor of \( a_{12} \)**:  
   The minor \( M_{12} \) is the determinant of the matrix obtained by deleting the first row and second column:

$$
M_{12} = \begin{vmatrix} 3 \end{vmatrix} = 3
$$

Thus, the cofactor \( A_{12} \) is:

$$
A_{12} = (-1)^{1+2} M_{12} = -1 \times 3 = -3
$$

3. **Minor of \( a_{21} \)**:  
   The minor \( M_{21} \) is the determinant of the matrix obtained by deleting the second row and first column:

$$
M_{21} = \begin{vmatrix} 2 \end{vmatrix} = 2
$$

Thus, the cofactor \( A_{21} \) is:

$$
A_{21} = (-1)^{2+1} M_{21} = -1 \times 2 = -2
$$

4. **Minor of \( a_{22} \)**:  
   The minor \( M_{22} \) is the determinant of the matrix obtained by deleting the second row and second column:

$$
M_{22} = \begin{vmatrix} 1 \end{vmatrix} = 1
$$

Thus, the cofactor \( A_{22} \) is:

$$
A_{22} = (-1)^{2+2} M_{22} = 1 \times 1 = 1
$$

Now, the **adjoint** of \( X \) is:

$$
\text{adj}(X) = \begin{bmatrix} 4 & -3 \\ -2 & 1 \end{bmatrix}
$$

Finally, the **inverse** of \( X \) is given by:

$$
X^{-1} = \frac{\text{adj}(X)}{|X|} = \frac{1}{-2} \cdot \begin{bmatrix} 4 & -3 \\ -2 & 1 \end{bmatrix}
$$

Thus:

$$
X^{-1} = \begin{bmatrix} -2 & 1.5 \\ 1 & -0.5 \end{bmatrix}
$$


In [ ]:
import numpy as np

# Define Matrix X
X = np.array([[1, 2], [3, 4]])

# Inverse of X
X_inv = np.linalg.inv(X)

# Inverse of Inverse
X_inv_inv = np.linalg.inv(X_inv)

# Matrix Multiplication Property (Inverse)
Y = np.array([[5, 6], [7, 8]])
XY_inv = np.linalg.inv(np.dot(X, Y))
YX_inv = np.linalg.inv(np.dot(Y, X))

# Determinant of X
det_X = np.linalg.det(X)

# Minor, Cofactor, and Adjoint Example
# For simplicity, let's use a 2x2 matrix
A = np.array([[1, 2], [3, 4]])

# Minor of A11 (remove the first row and first column)
minor_A11 = A[1, 1]

# Cofactor of A11 (multiply by (-1)^(1+1))
cofactor_A11 = (-1)**(1+1) * minor_A11

# Minor of A12 (remove the first row and second column)
minor_A12 = A[1, 0]

# Cofactor of A12 (multiply by (-1)^(1+2))
cofactor_A12 = (-1)**(1+2) * minor_A12

# Minor of A21 (remove the second row and first column)
minor_A21 = A[0, 1]

# Cofactor of A21 (multiply by (-1)^(2+1))
cofactor_A21 = (-1)**(2+1) * minor_A21

# Minor of A22 (remove the second row and second column)
minor_A22 = A[0, 0]

# Cofactor of A22 (multiply by (-1)^(2+2))
cofactor_A22 = (-1)**(2+2) * minor_A22

# Adjoint of A (for 2x2 matrix, adj(A) = [Cofactor_A11 Cofactor_A12; Cofactor_A21 Cofactor_A22])
adj_A = np.array([[cofactor_A11, cofactor_A12],
                  [cofactor_A21, cofactor_A22]])

# Inverse of A (A_inv = adj(A) / det(X))
A_inv = adj_A / det_X

print("X Inverse:\n", X_inv)
print("Inverse of Inverse:\n", X_inv_inv)
print("XY Inverse:\n", XY_inv)
print("YX Inverse:\n", YX_inv)
print("Determinant of X:", det_X)
print("Cofactor of A11:", cofactor_A11)
print("Cofactor of A12:", cofactor_A12)
print("Cofactor of A21:", cofactor_A21)
print("Cofactor of A22:", cofactor_A22)
print("Adjoint of A:\n", adj_A)
print("Inverse of A:\n", A_inv)


X Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of Inverse:
 [[1. 2.]
 [3. 4.]]
XY Inverse:
 [[ 12.5   -5.5 ]
 [-10.75   4.75]]
YX Inverse:
 [[11.5  -8.5 ]
 [-7.75  5.75]]
Determinant of X: -2.0000000000000004
Cofactor of A11: 4
Cofactor of A12: -3
Cofactor of A21: -2
Cofactor of A22: 1
Adjoint of A:
 [[ 4 -3]
 [-2  1]]
Inverse of A:
 [[-2.   1.5]
 [ 1.  -0.5]]


### Orthogonal & Orthonormal Vectors

#### 1. **Orthogonal Vectors**  
Two vectors \( X \) and \( Y \) are said to be orthogonal if their dot product is zero:

$$
X \cdot Y = 0
$$

For example, consider the vectors:

$$
X = \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \quad Y = \begin{bmatrix} -2 \\ 1 \end{bmatrix}
$$

The dot product of \( X \) and \( Y \) is:

$$
X \cdot Y = (1 \cdot -2) + (2 \cdot 1) = -2 + 2 = 0
$$

Since the dot product is zero, \( X \) and \( Y \) are orthogonal.

---

#### 2. **Orthonormal Vectors**  
A set of vectors \( \{X_1, X_2, X_3, ..., X_n\} \) is said to be orthonormal if:

1. Each pair of vectors is orthogonal:  
   $$ X_i \cdot X_j = 0 \quad \text{for} \quad i \neq j $$

2. Each vector has unit length (norm 1):  
   $$ X_i \cdot X_i = ||X_i||^2 = 1 $$

For example, consider the vectors:

$$
X_1 = \begin{bmatrix} \frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \end{bmatrix}, \quad X_2 = \begin{bmatrix} \frac{-1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \end{bmatrix}
$$

We check orthogonality:

$$
X_1 \cdot X_2 = \left(\frac{1}{\sqrt{2}} \cdot \frac{-1}{\sqrt{2}}\right) + \left(\frac{1}{\sqrt{2}} \cdot \frac{1}{\sqrt{2}}\right) = -\frac{1}{2} + \frac{1}{2} = 0
$$

Next, we check if each vector has unit length:

$$
X_1 \cdot X_1 = \left(\frac{1}{\sqrt{2}}\right)^2 + \left(\frac{1}{\sqrt{2}}\right)^2 = \frac{1}{2} + \frac{1}{2} = 1
$$

Similarly:

$$
X_2 \cdot X_2 = \left(\frac{-1}{\sqrt{2}}\right)^2 + \left(\frac{1}{\sqrt{2}}\right)^2 = \frac{1}{2} + \frac{1}{2} = 1
$$

Since both vectors are orthogonal and have unit length, \( X_1 \) and \( X_2 \) are orthonormal.

---

#### 3. **Orthogonal Matrix**  
A square matrix \( X \) is said to be orthogonal if:

$$
X^T X = I \quad \text{or} \quad X = X^{-1}
$$

For example, consider the matrix:

$$
X = \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{-1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \end{bmatrix}
$$

We check if the matrix is orthogonal by computing \( X^T X \):

$$
X^T = \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\ \frac{-1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \end{bmatrix}
$$

Now, compute \( X^T X \):

$$
X^T X = \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\ \frac{-1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \end{bmatrix} \times \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{-1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \end{bmatrix}
$$

Calculating the individual elements:

$$
X^T X = \begin{bmatrix} \frac{1}{2} + \frac{1}{2} & \frac{-1}{2} + \frac{1}{2} \\ \frac{-1}{2} + \frac{1}{2} & \frac{1}{2} + \frac{1}{2} \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} = I
$$

Since \( X^T X = I \), the matrix \( X \) is orthogonal.


In [ ]:
import numpy as np

# Define vectors X and Y
X = np.array([1, 2])
Y = np.array([-2, 1])

# Dot product of X and Y (orthogonality check)
dot_product = np.dot(X, Y)

# Check if X and Y are orthogonal
if dot_product == 0:
    print("X and Y are orthogonal")
else:
    print("X and Y are not orthogonal")

# Orthonormal check for X1 and X2
X1 = np.array([1/np.sqrt(2), 1/np.sqrt(2)])
X2 = np.array([-1/np.sqrt(2), 1/np.sqrt(2)])

# Dot product check for orthogonality
dot_product_orthonormal = np.dot(X1, X2)

# Length check for unit vectors
length_X1 = np.linalg.norm(X1)
length_X2 = np.linalg.norm(X2)

if dot_product_orthonormal == 0 and length_X1 == 1 and length_X2 == 1:
    print("X1 and X2 are orthonormal")
else:
    print("X1 and X2 are not orthonormal")

# Check if matrix is orthogonal
X_matrix = np.array([[1/np.sqrt(2), -1/np.sqrt(2)], [1/np.sqrt(2), 1/np.sqrt(2)]])
X_transpose = X_matrix.T

# Check if X_transpose * X equals identity matrix
if np.allclose(np.dot(X_transpose, X_matrix), np.eye(2)):
    print("Matrix X is orthogonal")
else:
    print("Matrix X is not orthogonal")


X and Y are orthogonal
X1 and X2 are not orthonormal
Matrix X is orthogonal


### Eigenvalues & Eigenvectors

#### 1. **Eigenvalue Equation**  
Given a square matrix \( A \) of size \( n \times n \), a vector \( X \) of size \( n \times 1 \), and a scalar \( \lambda \), the following equation represents the eigenvalue problem:

$$
A X = \lambda X \quad \text{or} \quad (A - \lambda I) X = 0
$$

Where:
- \( \lambda \) is the eigenvalue.
- \( X \) is the eigenvector (non-zero).

#### 2. **Determinant Condition**  
Since \( X \) is a non-zero vector, for the equation to hold true, the determinant of the matrix \( (A - \lambda I) \) must be zero:

$$
|A - \lambda I| = 0
$$

This gives us the characteristic equation to solve for the eigenvalues \( \lambda \).

For a 2x2 matrix \( A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \), the determinant is:

$$
|A - \lambda I| = \begin{vmatrix} a-\lambda & b \\ c & d-\lambda \end{vmatrix} = (a-\lambda)(d-\lambda) - bc
$$

#### 3. **Symmetric Matrix Properties**  
If \( A \) is a symmetric matrix, the eigenvalues will be real, and the eigenvectors will be orthogonal.

#### 4. **Diagonalization**  
If \( P \) is an orthogonal matrix, the matrix \( A \) can be diagonalized as:

$$
Z = P^{-1} A P = P^T A P
$$

Where \( Z \) is a diagonal matrix containing the eigenvalues of \( A \).

---

### Example:

Consider the matrix \( A \):

$$
A = \begin{bmatrix} 4 & 1 \\ 2 & 3 \end{bmatrix}
$$

To find the eigenvalues and eigenvectors, we solve the characteristic equation:

$$
|A - \lambda I| = 0
$$

The characteristic equation is:

$$
\begin{vmatrix} 4-\lambda & 1 \\ 2 & 3-\lambda \end{vmatrix} = 0
$$

Expanding the determinant:

$$
(4-\lambda)(3-\lambda) - (1 \cdot 2) = 0
$$

$$
12 - 7\lambda + \lambda^2 - 2 = 0
$$

$$
\lambda^2 - 7\lambda + 10 = 0
$$

Solving for \( \lambda \) using the quadratic formula:

$$
\lambda = \frac{-(-7) \pm \sqrt{(-7)^2 - 4(1)(10)}}{2(1)} = \frac{7 \pm \sqrt{49 - 40}}{2} = \frac{7 \pm \sqrt{9}}{2} = \frac{7 \pm 3}{2}
$$

So, the eigenvalues are:

$$
\lambda_1 = 5, \quad \lambda_2 = 2
$$

To find the eigenvectors, we substitute each eigenvalue into \( (A - \lambda I)X = 0 \) and solve for \( X \).


In [ ]:
import numpy as np

# Define matrix A
A = np.array([[4, 1], [2, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display results
print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[5. 2.]
Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


### System of Linear Equations

A system of linear equations consists of multiple linear equations involving the same set of variables. The goal is to find the values of the variables that satisfy all the equations simultaneously. A general system of linear equations can be written as:

$$
\begin{aligned}
a_1x_1 + a_2x_2 + \dots + a_nx_n &= b_1 \\
c_1x_1 + c_2x_2 + \dots + c_nx_n &= b_2 \\
\vdots \\
z_1x_1 + z_2x_2 + \dots + z_nx_n &= b_m
\end{aligned}
$$

Where:
- \( x_1, x_2, \dots, x_n \) are the variables.
- \( a_1, a_2, \dots, a_n, c_1, c_2, \dots, z_1, z_2 \dots \) are the coefficients of the system.
- \( b_1, b_2, \dots, b_m \) are the constants on the right-hand side of the equations.

The system can be written in matrix form as:

$$
AX = B
$$

Where:
- \( A \) is a matrix of coefficients (size \( m \times n \)),
- \( X \) is the column vector of unknowns (size \( n \times 1 \)),
- \( B \) is the column vector of constants (size \( m \times 1 \)).

### Example:

Consider the following system of equations:

\[
\begin{aligned}
2x + 3y &= 5 \\
4x - y &= 3
\end{aligned}
\]

We can represent this system in matrix form:

\[
A = \begin{bmatrix} 2 & 3 \\ 4 & -1 \end{bmatrix}, \quad X = \begin{bmatrix} x \\ y \end{bmatrix}, \quad B = \begin{bmatrix} 5 \\ 3 \end{bmatrix}
\]

Thus, the system becomes:

$$
AX = B \quad \text{or} \quad \begin{bmatrix} 2 & 3 \\ 4 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 5 \\ 3 \end{bmatrix}
$$

### Solving the System:

We can solve the system of equations using various methods like:
1. **Substitution method**
2. **Elimination method**
3. **Matrix inversion** (if \( A \) is invertible)

Using the **matrix inversion method**, we first check if \( A \) is invertible. The inverse of \( A \) is calculated as:

$$
A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A)
$$

Then, the solution is given by:

$$
X = A^{-1}B
$$

---

### Calculation for the Example:

Given:

\[
A = \begin{bmatrix} 2 & 3 \\ 4 & -1 \end{bmatrix}, \quad B = \begin{bmatrix} 5 \\ 3 \end{bmatrix}
\]

1. **Determinant of \( A \):**

$$
\text{det}(A) = (2 \times -1) - (3 \times 4) = -2 - 12 = -14
$$

2. **Inverse of \( A \):**

The inverse of \( A \) is:

$$
A^{-1} = \frac{1}{\text{det}(A)} \cdot \text{adj}(A)
$$

The adjugate of \( A \), \( \text{adj}(A) \), is calculated by swapping the diagonal elements and changing the signs of the off-diagonal elements:

$$
\text{adj}(A) = \begin{bmatrix} -1 & -3 \\ -4 & 2 \end{bmatrix}
$$

Thus,

$$
A^{-1} = \frac{1}{-14} \begin{bmatrix} -1 & -3 \\ -4 & 2 \end{bmatrix} = \begin{bmatrix} \frac{1}{14} & \frac{3}{14} \\ \frac{4}{14} & \frac{-2}{14} \end{bmatrix}
$$

3. **Solving for \( X \):**

Now, multiply \( A^{-1} \) by \( B \) to find \( X \):

$$
X = A^{-1}B = \begin{bmatrix} \frac{1}{14} & \frac{3}{14} \\ \frac{4}{14} & \frac{-2}{14} \end{bmatrix} \begin{bmatrix} 5 \\ 3 \end{bmatrix}
$$

This gives:

$$
X = \begin{bmatrix} \frac{1}{14}(5) + \frac{3}{14}(3) \\ \frac{4}{14}(5) + \frac{-2}{14}(3) \end{bmatrix} = \begin{bmatrix} \frac{5 + 9}{14} \\ \frac{20 - 6}{14} \end{bmatrix} = \begin{bmatrix} \frac{14}{14} \\ \frac{14}{14} \end{bmatrix}
$$

Thus,

$$
X = \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

The solution to the system is:

$$
x = 1, \quad y = 1
$$

In [ ]:
import numpy as np

# Define the matrix A and vector B
A = np.array([[2, 3], [4, -1]])
B = np.array([5, 3])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Display the solution
print("Solution:", X)


Solution: [1. 1.]


### Rank of a Matrix

The **rank** of a matrix \( X \), denoted as \( r(X) \), is defined as the maximum number of linearly independent column vectors in the matrix. It can also be described as the maximum number of linearly independent rows.

### Properties of Rank:

1. **Rank and Linearly Independent Vectors**:
   For an \( n \times k \) matrix \( X \), if the column vectors are denoted as \( [x_1, x_2, \dots, x_k] \), the rank is the maximum number of linearly independent vectors in these columns.

2. **Full Rank**:
   If \( X \) is an \( n \times k \) matrix and \( r(X) = k \), the matrix \( X \) is said to be of **full rank** when \( n \geq k \). This means that all columns are linearly independent.

3. **Rank Invariance**:
   The rank of a matrix \( X \) remains the same when it is multiplied by a non-singular matrix on either side:
   
   $$ r(X) = r(X^T) = r(XX^T) $$

4. **Non-singularity**:
   For a square matrix \( X \) of size \( k \times k \), \( X \) is non-singular (invertible) if and only if the rank of \( X \) is equal to \( k \), i.e., \( r(X) = k \).

5. **Rank Preservation**:
   If \( X \) is an \( n \times k \) matrix, \( P \) is an \( n \times n \) non-singular matrix, and \( Q \) is a \( k \times k \) non-singular matrix, then:
   
   $$ r(X) = r(PX) = r(XQ) $$

6. **Rank of a Diagonal Matrix**:
   The rank of a diagonal matrix is equal to the number of non-zero diagonal entries. For example, for a diagonal matrix:
   
   $$ D = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} $$
   
   The rank is 2, because there are two non-zero diagonal elements.

7. **Rank Inequality**:
   The rank of the product of two matrices is less than or equal to the product of their individual ranks:
   
   $$ r(XY) \leq r(X) \cdot r(Y) $$

### Example:

Consider the matrix \( X \):

$$
X = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

#### Step 1: Find the Rank of \( X \)

To find the rank of \( X \), we can use Gaussian elimination or compute the row echelon form (REF).

The row echelon form of \( X \) is:

$$
\text{REF}(X) = \begin{bmatrix}
1 & 2 & 3 \\
0 & -3 & -6 \\
0 & 0 & 0
\end{bmatrix}
$$

From this, we can see that there are 2 non-zero rows, indicating that the rank of matrix \( X \) is 2.

Thus, \( r(X) = 2 \).

#### Step 2: Verify Properties

- The matrix is not of full rank because \( r(X) \neq 3 \), the number of columns.
- If \( P \) and \( Q \) are non-singular matrices of appropriate size, multiplying \( X \) by \( P \) or \( Q \) will not change its rank.
- The rank of the diagonal matrix \( D \) with non-zero diagonal elements is simply the number of non-zero elements.

In [ ]:
import numpy as np

# Define the matrix X
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the rank of X
rX = np.linalg.matrix_rank(X)

# Display the rank
print("Rank of X:", rX)


Rank of X: 2
